name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.4.app/Contents/Developer || sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: SwiftLint
        run: swiftlint --config .swiftlint.yml
      - name: SwiftFormat
        run: swiftformat . --lint --config .swiftformat
      - name: Build and test
        run: |
          xcodebuild -scheme UniApp -destination 'platform=iOS Simulator,name=iPhone 15' clean build test | xcpretty
        env:
          NSUnbufferedIO: YES
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: build/reports
          if-no-files-found: ignore
