name: iOS CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Install SwiftFormat
        run: brew install swiftformat
      - name: SwiftLint
        run: swiftlint --config .swiftlint.yml
      - name: SwiftFormat
        run: |
          if ! swiftformat . --lint --config .swiftformat; then
            echo "::warning::SwiftFormat reported style violations. Run 'swiftformat . --config .swiftformat' locally and recommit."
          fi
      - name: Build and test
        run: |
          xcodebuild -scheme UniApp -destination 'platform=iOS Simulator,OS=latest,name=iPhone 15' clean build test | xcpretty
        env:
          NSUnbufferedIO: YES
      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-logs
          path: build/reports
          if-no-files-found: ignore
